FROM golang:1.12.1-alpine3.9 as build
RUN apk add --no-cache git curl

RUN curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl

RUN mkdir -p /go/src/app
WORKDIR /go/src/app

RUN go get github.com/julienschmidt/httprouter
RUN go get github.com/sirupsen/logrus

COPY ./src /go/src/app/

RUN go build -o app
################################################################################################################

FROM python:3.6.8-alpine3.9

COPY --from=build /usr/local/bin/youtube-dl /usr/local/bin/youtube-dl
RUN chmod a+rx /usr/local/bin/youtube-dl

RUN mkdir -p /app
COPY --from=build /go/src/app/app /app/
WORKDIR /app

CMD ["./app"]
