FROM golang:1.12.1-alpine3.9 as build
RUN apk add --no-cache git
COPY ./src /src
WORKDIR /src
RUN go get github.com/julienschmidt/httprouter
RUN go get github.com/sirupsen/logrus
RUN cd /src && go build -o app
################################################################################################################

FROM python:3.6.8-alpine3.9

RUN mkdir -p /downloader && cd /downloader && \
    curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && \
    chmod a+rx /usr/local/bin/youtube-dl

RUN mkdir -p /app
COPY --from=build /src/app /app
WORKDIR /app

CMD ["./app"]
