FROM golang:1.12.1-alpine3.9 as build
RUN apk add --no-cache git curl

RUN curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl

RUN mkdir -p /go/src/app
WORKDIR /go/src/app

RUN go get github.com/julienschmidt/httprouter
RUN go get github.com/sirupsen/logrus
RUN go get github.com/streadway/amqp
RUN go get github.com/go-kivik/kivik
RUN go get github.com/go-kivik/couchdb
RUN go get github.com/rs/xid
RUN go get github.com/h2so5/goback/regexp

COPY ./src /go/src/app/

RUN go build -o app
################################################################################################################

FROM python:3.6.8-alpine3.9

RUN apk update && apk add --no-cache ffmpeg
COPY --from=build /usr/local/bin/youtube-dl /usr/local/bin/youtube-dl
RUN chmod a+rx /usr/local/bin/youtube-dl

RUN touch /etc/youtube-dl.conf && echo '-o /data/%(title)s.%(ext)s' >> /etc/youtube-dl.conf
RUN mkdir -p /app
COPY --from=build /go/src/app/app /app/
WORKDIR /app

CMD ["./app"]
