FROM golang:1.14.0-alpine3.11 as build
RUN apk add --no-cache git curl

RUN curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl

WORKDIR /app/src/

COPY ./src/go.mod /app/src/
COPY ./src/go.sum /app/src/

RUN go mod download

COPY ./src/ /app/src/

RUN go build -o app
# ################################################################################################################

FROM python:3.7.7-alpine3.11

RUN apk update && apk add --no-cache ffmpeg
COPY --from=build /usr/local/bin/youtube-dl /usr/local/bin/youtube-dl
RUN chmod a+rx /usr/local/bin/youtube-dl

RUN touch /etc/youtube-dl.conf && echo '-o /data/%(title)s.%(ext)s' >> /etc/youtube-dl.conf
RUN mkdir -p /app
COPY --from=build /app/src/app /app/

WORKDIR /app
CMD ["./app"]
